// Empacota as entradas do @thoth/shared em CommonJS autocontido.
//
// Why: dependencies like sanitize-html pull in htmlparser2, which is ESM-only.
// Sob `require` em Node < 22 (ex.: o worker roda na imagem do Playwright com
// Node 20) that would throw ERR_REQUIRE_ESM. Bundling with esbuild transpiles those
// ESM dependencies into the CJS bundle, making the artifact independent
// of the Node version. The .d.ts files are generated by tsc (--emitDeclarationOnly).
import * as esbuild from 'esbuild';

const common = {
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node20',
  logLevel: 'error',
  // Keep only Node builtins external (the default for platform=node).
};

await esbuild.build({
  ...common,
  entryPoints: ['src/index.ts'],
  outfile: 'dist/index.js',
});

await esbuild.build({
  ...common,
  entryPoints: ['src/node/index.ts'],
  outfile: 'dist/node/index.js',
});

// eslint-disable-next-line no-console
console.log('[shared] bundles CJS gerados: dist/index.js, dist/node/index.js');
