#!/usr/bin/env bash
# THOTH restore from a dump generated by deploy/backup.sh.
#
# Usage:  ./deploy/restore.sh backups/thoth-db-YYYYMMDD-HHMMSS.sql.gz
set -euo pipefail

FILE="${1:?provide the .sql.gz backup file}"
[ -f "$FILE" ] || { echo "file not found: $FILE"; exit 1; }

DB_USER="${POSTGRES_USER:-thoth}"
DB_NAME="${POSTGRES_DB:-thoth}"

echo "[restore] WARNING: this overwrites the current data in '$DB_NAME'."
read -r -p "Continue? (type 'yes'): " CONFIRM
[ "$CONFIRM" = "yes" ] || { echo "aborted."; exit 1; }

echo "[restore] restoring from $FILE ..."
gunzip -c "$FILE" | docker compose exec -T db psql -U "$DB_USER" -d "$DB_NAME"

echo "[restore] done. Use the SAME ENCRYPTION_KEY as the backup to read encrypted fields."
